import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import KeyVault from '@/components/KeyVault';

export const metadata = {
  title: 'Question Bank',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  // THEME INJECTION
                  var theme = localStorage.getItem('theme');
                  var prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
                  if (theme === 'dark' || (!theme && prefersDark)) {
                    document.documentElement.setAttribute('data-theme', 'dark');
                  } else {
                    document.documentElement.setAttribute('data-theme', 'light');
                  }
                  
                  // SECURE KEY INJECTION - Applies payload instantly before React mounts!
                  var m = localStorage.getItem('custom_mongo');
                  var g = localStorage.getItem('custom_gemini');
                  if (m && g) {
                     var originalFetch = window.fetch;
                     window.fetch = async function(...args) {
                        var resource = args[0];
                        var config = args[1] || {};
                        if (typeof resource === 'string' && resource.startsWith('/api/')) {
                           config.headers = config.headers || {};
                           config.headers['x-mongo-uri'] = m;
                           config.headers['x-gemini-key'] = g;
                           args[1] = config;
                        }
                        return originalFetch.apply(window, args);
                     };
                  }
                } catch (e) {}
              })();
            `,
          }}
        />
      </head>
      <body>
        <KeyVault />
        <Header />
        <div className="page-wrapper">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
